c this is <time_add.f> (extracted from ../libtime.f)
c automatically generated by "SPLITF.PL   V1.0   SPLIT Fortran source code"
c----------------------------------------------------------------------
c $Id: time_add.f,v 2.1 2000/08/06 12:00:39 thof Exp $
c
c 05/08/2000 by Thomas Forbriger (IfG Stuttgart)
c
c add two time records
c
c REVISIONS and CHANGES
c    05/08/2000   V1.0   Thomas Forbriger
c                 V2.0   call language specific warning routine
c
c ============================================================================
cS
      subroutine time_add(date1, date2, date3)
c
c date3=date1+date2
c
c One of both should be a relative time: 
c   relative + absolute -> absolute
c   relative + relative -> relative
c   absolute + absolute -> senseless
c
c NOTICE: This version of time_add disregards leap-seconds!
c
c input:
c   date1:  primary time record
c   date2:  time record to be added
c output:
c   date3:  date1+date2       the sum of the input record
c
c last change: V2.00 (05/08/2000)
c
      integer date1(7), date2(7), date3(7)
cE
      integer i
c
      if((date1(1).ne.0).and.(date2(1).ne.0)) call 
     &  time_util_warning('time_add)',
     &                    'adding two absolute times is senseless')
      call time_norm(date1)
      call time_norm(date2)
      do i=1,7
        date3(i)=date1(i)+date2(i)
      enddo
      call time_norm(date3)
      return
      end
c
c ----- END OF <time_add.f> -----
