c this is <time_copy.f> (extracted from ../libtime.f)
c automatically generated by "SPLITF.PL   V1.0   SPLIT Fortran source code"
c----------------------------------------------------------------------
c $Id: time_copy.f,v 2.0 2000/08/05 21:58:30 thof Stab $
c
c 05/08/2000 by Thomas Forbriger (IfG Stuttgart)
c
c copy time record
c
c REVISIONS and CHANGES
c    05/08/2000   V2.0   Thomas Forbriger
c
c ============================================================================
cS
      subroutine time_copy(date1, date2)
c
c copy: date1 --> date2
c
c input:
c   date1:  any time record
c output:
c   date2:  copy of date1
c
c last change: V2.00 (05/08/2000)
c
      integer date1(7), date2(7)
cE
      integer i
c
      do i=1,7
        date2(i)=date1(i)
      enddo
      return
      end
c
c ----- END OF <time_copy.f> -----
