c this is <time_div.f> (extracted from ../libtime.f)
c automatically generated by "SPLITF.PL   V1.0   SPLIT Fortran source code"
c----------------------------------------------------------------------
c $Id: time_div.f,v 2.1 2000/08/06 19:55:19 thof Exp $
c
c 05/08/2000 by Thomas Forbriger (IfG Stuttgart)
c
c divide relative time record by an integer
c
c REVISIONS and CHANGES
c    05/08/2000   V1.0   Thomas Forbriger
c                 V2.0   call language specific fatal error wrapper
c
c ============================================================================
cS
      subroutine time_div(date1, date2, n, rest)
c
c Divide relative time 'date1' by integer 'n' and store result in 'date2'.
c 'rest' gives the none dividable rest in microseconds.
c
c input:
c   date1:  relative time value to be divided
c   n:      divisor
c output:
c   date2:  date1/n           regularized relative time value
c   rest:   date1-(n*date2)   integer number of microseconds
c 
c always: date1 >= (n*date2)
c
c last change: V2.00 (05/08/2000)
c
      integer date1(7), date2(7), n, rest
cE
      integer carry, limit(7), help, i
      data limit/-1,-1,24,60,60,1000,1000/
c
      if (date1(1).ne.0) then
        call time_util_fatal('(time_div)','no absolute time allowed')
      else
        carry=0
        do i=2,7
          help=date1(i)+carry*limit(i)
          date2(i)=int(help/n)
          carry=help-n*date2(i)
        enddo
        rest=carry
        date2(1)=0
        call time_norm(date2)
      endif
      return
      end
c
c ----- END OF <time_div.f> -----
