c this is <time_clear.f> (extracted from ../libtime.f)
c automatically generated by "SPLITF.PL   V1.0   SPLIT Fortran source code"
c----------------------------------------------------------------------
c $Id: time_clear.f,v 2.0 2000/08/05 21:58:30 thof Stab $
c
c 05/08/2000 by Thomas Forbriger (IfG Stuttgart)
c
c clear a time record (i.e. set all values to zero)
c
c REVISIONS and CHANGES
c    05/08/2000   V2.0   Thomas Forbriger
c
c ============================================================================
cS
      subroutine time_clear(date)
c
c clear a time record (i.e. set all values to zero)
c
c input/output:
c   date:   time record to be cleared
c
c last change: V2.00 (05/08/2000)
c
      integer date(7)
cE
      integer i
c
      do i=1,7
        date(i)=0
      enddo
      return
      end
c
c ----- END OF <time_clear.f> -----
