c this is <time_finish.f> (extracted from ../libtime.f)
c automatically generated by "SPLITF.PL   V1.0   SPLIT Fortran source code"
c----------------------------------------------------------------------
c $Id: time_finish.f,v 2.0 2000/08/05 21:58:30 thof Stab $
c
c 05/08/2000 by Thomas Forbriger (IfG Stuttgart)
c
c finish setting of absolute time records.
c
c REVISIONS and CHANGES
c    05/08/2000   V2.0   Thomas Forbriger
c
c ============================================================================
cS
      subroutine time_finish(date)
c
c Finish setting of absolute time value. This routine is senseless
c in combination with relative time values (year=0). This routine just calls
c time_fullyear on the year value and than time_norm for the whole record.
c
c input/output:
c   date:   absolute time record to be regularized
c
c last change: V2.00 (05/08/2000)
c
      integer date(7)
cE
      call time_fullyear(date(1))
      call time_norm(date)
      return
      end
c
c ----- END OF <time_finish.f> -----
