c this is <time_sprint.f> (extracted from ../libtime.f)
c automatically generated by "SPLITF.PL   V1.0   SPLIT Fortran source code"
c----------------------------------------------------------------------
c $Id: time_sprint.f,v 2.0 2000/08/05 21:58:30 thof Stab $
c
c 05/08/2000 by Thomas Forbriger (IfG Stuttgart)
c
c print date value to string
c NOTICE: this routine is very language specific ;-)
c
c REVISIONS and CHANGES
c    05/08/2000   V2.0   Thomas Forbriger
c
c ============================================================================
cS
      subroutine time_sprint(date, string)
c 
c Print date to string (string must be 35 characters long at least)
c
c input:
c   date:   date record to be printed
c output:
c   string: text representation of date value
c
c last change: V2.00 (05/08/2000)
c
      integer date(7)
      character*(*) string
cE
      character*(35) ostring
      integer i, day, month, d(7)
c 
      call time_copy(date, d)
      call time_norm(d)
c check for relative date
      if (d(1).gt.0) then
        call time_getdate(day, month, d)
        write(ostring, 1) d(2), day, month, d(1), (d(i), i=3,7)
    1   format(i3.3,1x,2(i2.2,1h/),i4.4,1x,i2.2,2(1h:,i2.2),1h.,2(i3.3))
      else
        if (d(2).eq.1) then
          write(ostring, 2) (d(i), i=2,7)
        else
          write(ostring, 3) (d(i), i=2,7)
        endif
    2   format(i5,' day ',i2.2,2(1h:,i2.2),1h.,2(i3.3))
    3   format(i5,' days ',i2.2,2(1h:,i2.2),1h.,2(i3.3))
      endif
      string=ostring
      return
      end
c
c ----- END OF <time_sprint.f> -----
