c this is <time_libversion.f> (extracted from ../libtime.f)
c automatically generated by "SPLITF.PL   V1.0   SPLIT Fortran source code"
c----------------------------------------------------------------------
c $Id: time_libversion.f,v 2.1 2000/08/06 15:25:57 thof Exp $
c
c 05/08/2000 by Thomas Forbriger (IfG Stuttgart)
c
c return the current version of the libtime FORTRAN kernel
c
c REVISIONS and CHANGES
c    05/08/2000   V1.0   Thomas Forbriger
c    05/08/2000   V2.0   extracted from libtime.f
c
c ============================================================================
cS
      real function time_libversion()
c
c returns the current version of the FORTRAN library kernel
c
c last change: V2.00 (05/08/2000)
c
cE
      real version
      parameter(version=2.00)
      time_libversion=version
      return
      end
c
c ----- END OF <time_libversion.f> -----
