c this is <time_compare.f> (extracted from ../libtime.f)
c automatically generated by "SPLITF.PL   V1.0   SPLIT Fortran source code"
c----------------------------------------------------------------------
c $Id: time_compare.f,v 2.1 2000/08/06 14:08:47 thof Exp $
c
c 05/08/2000 by Thomas Forbriger (IfG Stuttgart)
c
c compare two time records
c
c REVISIONS and CHANGES
c    05/08/2000   V1.0   Thomas Forbriger
c                 V2.0   call language specific warning wrapper
c
c ============================================================================
cS
      integer function time_compare(date1, date2)
c
c Compare values of date1 and date2. 
c Both must be absolute or both must be relative.
c
c result = 0   for   date1 = date2
c result = -1  for   date1 < date2
c result = 1   for   date1 > date2
c
c input:
c   date1:  primary time record
c   date2:  secondary time record
c
c last change: V2.00 (05/08/2000)
c
      integer date1(7), date2(7)
cE
      integer result, i
c 
      if (((date1(1).eq.0).and.(date2(1).eq.0)).or.
     &    ((date1(1).ne.0).and.(date2(1).ne.0))) then
        result=0
        i=1
    1   if (date1(i).gt.date2(i)) then
          result=1
        elseif (date1(i).lt.date2(i)) then
          result=-1
        else
          i=i+1
          if (i.lt.8) goto 1
        endif
      else
        call time_util_warning('time_compare',
     &                         'do not mix absolute and relative times')
        call time_util_warning('time_compare',
     &                         'routine skipped... (result=-2)')
        result=-2
      endif
      time_compare=result
      return
      end
c
c ----- END OF <time_compare.f> -----
