#!/usr/bin/env bash
#########################################################
#  script to invoke minimal_simulation 
#########################################################
IBMLIB_DIR=../..
export TESTDIR=$PWD
#
rm -f config.mk.save
if [ -e $IBMLIB_DIR/config.mk ]; then 
   cp $IBMLIB_DIR/config.mk config.mk.save
fi
cp config.mk $IBMLIB_DIR/config.mk
echo "result test_output: compilation/runtime error" > test_summary # overwritten by ibmrun_test
#

#
# ====== compile and run test ======
#
cd $IBMLIB_DIR; make ibmrun_test; cd ${TESTDIR}
$IBMLIB_DIR/ibmrun_test simpar1 > /dev/null # writes test_summary
#
# ====== restore + clean up ======
#
rm -f $IBMLIB_DIR/ibmrun_test
if [ -e config.mk.save ]; then 
   mv config.mk.save $IBMLIB_DIR/config.mk
fi
#
