#!/bin/sh
#
ln -s  Setups/common_rules.mk 
#                     
ln -s  Setups/Compilers/ifort/compiler_defaults.mk 
#
cat>config.mk<<EOF
EXECUTABLE          = ibmrun
PHYSICAL_FIELDS_DIR = oceanography_providers/linear_field
PARTICLE_STATE_DIR  = biology_providers/passive
TASK_DIR            = task_providers/basic_simulation
EOF
#
